function OTPmessage(to, name, otp) {
  const x = ```
    <h1>Travera</h1>
    <h4>The Travel Dictionary</h4>
    <p>Hi, ${name}</p>
    <p>Your OTP is <b>${otp}</b></p>
    <p>Thanks, for joining us, please do not share this otp if not generated by you.</p>
    ```;
  return x;
}
